# Generated by Django 4.1.3 on 2022-11-17 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doc_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('doc_name', models.CharField(max_length=100)),
                ('doc_adhaar', models.CharField(max_length=15)),
                ('doc_wallet', models.CharField(max_length=50)),
                ('issue_center', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.CharField(default='None', max_length=50, primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_adhaar', models.CharField(max_length=15)),
                ('patient_wallet', models.CharField(max_length=50)),
                ('issue_center', models.CharField(max_length=50)),
            ],
        ),
    ]
