# Generated by Django 4.1.3 on 2022-11-18 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backedn', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('file_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('file_hash', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Records',
            fields=[
                ('record_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('records', models.JSONField()),
            ],
        ),
    ]
