# Generated by Django 4.1.3 on 2022-12-01 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backedn', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emergency',
            fields=[
                ('id', models.CharField(default='None', max_length=100, primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.CharField(default='None', max_length=100, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.CharField(default='None', max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=15)),
            ],
        ),
    ]
