# Generated by Django 4.1.3 on 2022-11-18 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backedn', '0002_file_records'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDoctors',
            fields=[
                ('patient_id', models.CharField(default='None', max_length=50, primary_key=True, serialize=False)),
                ('doctors', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.CharField(default='None', max_length=100, primary_key=True, serialize=False)),
                ('premission_type', models.CharField(max_length=5)),
            ],
        ),
        migrations.AlterField(
            model_name='records',
            name='records',
            field=models.TextField(),
        ),
    ]
