# Generated by Django 4.1.3 on 2022-12-01 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backedn', '0002_emergency_login_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.CharField(default='None', max_length=50, primary_key=True, serialize=False)),
                ('otp', models.CharField(max_length=10)),
            ],
        ),
    ]
