# Generated by Django 4.1.3 on 2022-11-16 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backedn', '0003_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='patient_id',
        ),
        migrations.AddField(
            model_name='patient',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
