# Generated by Django 4.1.3 on 2022-11-16 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backedn', '0004_remove_patient_patient_id_patient_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='id',
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_id',
            field=models.CharField(default='None', max_length=50, primary_key=True, serialize=False),
        ),
    ]
