# Generated by Django 4.1.3 on 2022-11-16 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backedn', '0005_remove_patient_id_patient_patient_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
